import { ContentPlanSchema } from './schemas';

const CHECKED_AT = '2026-07-24T00:00:00.000Z';

function platforms(
  linkObjective: 'none' | 'source' | 'case-study' | 'portfolio',
) {
  return {
    instagram: {
      platform: 'instagram',
      format: 'Carousel 1080 × 1350 px',
      assetCount: 6,
      copyRule:
        'Vizuálne vysvetlenie; caption pridá kontext, 2–5 hashtagov a bez surového URL.',
      linkObjective,
    },
    linkedin: {
      platform: 'linkedin',
      format: 'Flattenovaný PDF dokument',
      assetCount: 6,
      copyRule:
        'Konkrétny trade-off, jeden dôkaz a vlastný pohľad Rise; 0–3 hashtagy.',
      linkObjective,
    },
    facebook: {
      platform: 'facebook',
      format: 'Jeden hlavný obrázok alebo 2–3 zoradené obrázky',
      assetCount: 3,
      copyRule:
        'Pokojné vysvetlenie do 900 znakov; nekopírovať LinkedIn text.',
      linkObjective,
    },
  };
}

const LEGACY_CONTENT_PLAN = {
  id: 'rise-awareness-2026-q3',
  objective: 'brand-awareness',
  audience: 'Majitelia a vedenie rastúcich firiem na Slovensku.',
  startsOn: '2026-07-28',
  endsOn: '2026-10-24',
  updatedAt: CHECKED_AT,
  projects: [
    {
      id: 'mapatrhu',
      name: 'MapaTrhu',
      level: 'public-owned',
      publicUrl: 'https://rise.sk/portfolio/trh-nehnutelnosti',
      allowedClaimIds: ['claim-mapatrhu'],
      allowedClaims: [
        'Verejný produkt spája mapu, ponuky, cenový kontext, lokalitu a porovnanie.',
      ],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: ['Osobné údaje, neverejné dáta a interné produktové metriky.'],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
    {
      id: 'slates',
      name: 'Slates',
      level: 'public-case-study',
      publicUrl: 'https://rise.sk/portfolio/slates',
      allowedClaimIds: ['claim-slates'],
      allowedClaims: [
        'Verejná castingová platforma a vysoká úroveň jej moderného technického základu.',
      ],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: [
        'Mená talentov, interné implementačné detaily a časový údaj bez samostatného schválenia.',
      ],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
    {
      id: 'grantai',
      name: 'GrantAI',
      level: 'public-owned',
      publicUrl: 'https://rise.sk/portfolio/grant-ai',
      allowedClaimIds: ['claim-grantai'],
      allowedClaims: [
        'Verejný grantový produkt vedie od otvorenej výzvy po riadený pracovný tok.',
      ],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: ['Údaje používateľov a rozpracované grantové žiadosti.'],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
    {
      id: 'moja-firma',
      name: 'MojaFirma',
      level: 'public-owned',
      publicUrl: 'https://rise.sk/portfolio/ai-erp',
      allowedClaimIds: ['claim-mojafirma'],
      allowedClaims: [
        'Vlastný produkt spája dokumenty, financie a úlohy do jedného pracovného toku.',
      ],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: ['Reálne faktúry, firmy, sumy a osobné údaje.'],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
    {
      id: 'payroll',
      name: 'Personálno-mzdový systém',
      level: 'confidential-anonymized',
      publicUrl: 'https://rise.sk/portfolio/personalno-mzdovy-system',
      allowedClaimIds: ['claim-confidentiality'],
      allowedClaims: [
        'Verejne opísaný anonymizovaný pracovný tok a verejné demo Horilla.',
      ],
      allowedVisuals: [
        'ui-flow',
        'branded-diagram',
        'public-composite',
        'anonymous-editorial',
      ],
      prohibited: ['Klient, klientsky systém, skutoční zamestnanci a neodobrené metriky.'],
      requiresBriefApproval: true,
      requiresVisualApproval: true,
      note: 'Každý vizuál musí uviesť, že ide o verejné demo, nie klientsky systém.',
    },
    {
      id: 'smartgym',
      name: 'SmartGym',
      level: 'public-case-study',
      publicUrl: 'https://rise.sk/portfolio/smartgym',
      allowedClaimIds: ['claim-smartgym'],
      allowedClaims: [
        'Verejná case study opisuje spoločný stav členstva pre mobil, web a vstupné zariadenie.',
      ],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: ['Mená členov, QR kódy, interná administrácia a nové výsledky.'],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
    {
      id: 'viac-ako-nick',
      name: 'VIAC AKO NI(c)K',
      level: 'approval-required',
      publicUrl: 'https://rise.sk/portfolio/viac-ako-nick',
      allowedClaimIds: ['claim-viac-nick'],
      allowedClaims: ['Iba presné fakty a obrazovky z verejne publikovanej case study.'],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: ['Konverzácie, identity, citlivé prípady a údaje používateľov.'],
      requiresBriefApproval: true,
      requiresVisualApproval: true,
    },
    {
      id: 'trnava',
      name: 'Rozvoj dopravy Trnava',
      level: 'public-case-study',
      publicUrl: 'https://rise.sk/portfolio/rozvoj-dopravy-trnava',
      allowedClaimIds: ['claim-trnava'],
      allowedClaims: [
        'Verejný analytický pohľad spája mapu, linky, zastávky, tabuľky a grafy.',
      ],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: ['Interné mestské dáta a nepodložené dopady.'],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
    {
      id: 'running-app',
      name: 'Bežecká mobilná aplikácia',
      level: 'confidential-anonymized',
      publicUrl: 'https://rise.sk/portfolio/bezecka-mobilna-aplikacia',
      allowedClaimIds: ['claim-running-app'],
      allowedClaims: ['Anonymizovaný mobilný proces bez klienta a výsledkov.'],
      allowedVisuals: ['branded-diagram', 'public-composite', 'anonymous-editorial'],
      prohibited: ['Reálne produktové UI, klient, používateľské dáta a metriky.'],
      requiresBriefApproval: true,
      requiresVisualApproval: true,
    },
    {
      id: 'rise-sk',
      name: 'Rise.sk',
      level: 'public-owned',
      publicUrl: 'https://rise.sk/portfolio/rise-sk',
      allowedClaimIds: ['claim-testing', 'claim-modernization'],
      allowedClaims: [
        'Verejný vývoj webu, lokalizácií, portfólia, prístupnosti a pohybu.',
      ],
      allowedVisuals: [
        'real-ui',
        'ui-flow',
        'branded-diagram',
        'before-after',
        'public-composite',
      ],
      prohibited: ['Nezverejnené konverzné alebo klientské dáta.'],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
    {
      id: 'rastlinkovo',
      name: 'Rastlinkovo',
      level: 'public-case-study',
      publicUrl: 'https://rise.sk/portfolio/rastlinkovo',
      allowedClaimIds: ['claim-rastlinkovo'],
      allowedClaims: [
        'Optimalizácia existujúceho verejného WooCommerce obchodu.',
      ],
      allowedVisuals: ['real-ui', 'ui-flow', 'branded-diagram', 'public-composite'],
      prohibited: ['Tržby, konverzie, objednávky a interná administrácia.'],
      requiresBriefApproval: false,
      requiresVisualApproval: false,
    },
  ],
  trends: [
    {
      id: 'ai-act-transparency',
      title: 'Transparentnostné povinnosti podľa AI Act',
      url: 'https://digital-strategy.ec.europa.eu/en/news/commission-opens-consultation-draft-guidelines-ai-transparency-obligations',
      publisher: 'European Commission',
      sourceKind: 'primary',
      publishedAt: '2026-05-08T00:00:00.000Z',
      checkedAt: CHECKED_AT,
      expiresAt: '2026-08-06T23:59:59.000Z',
      scope:
        'Transparentnostné povinnosti od 2. augusta 2026; obsah nie je právne poradenstvo.',
    },
    {
      id: 'openai-presence',
      title: 'OpenAI Presence',
      url: 'https://openai.com/index/introducing-openai-presence/',
      publisher: 'OpenAI',
      sourceKind: 'primary',
      publishedAt: '2026-07-22T00:00:00.000Z',
      checkedAt: CHECKED_AT,
      expiresAt: '2026-08-25T23:59:59.000Z',
      scope:
        'Konkrétna produktová aktualizácia o politikách, guardrails, evaloch a eskalácii agentov.',
    },
    {
      id: 'google-managed-agents',
      title: 'Managed Agents in Gemini API',
      url: 'https://blog.google/innovation-and-ai/technology/developers-tools/expanding-managed-agents-gemini-api/',
      publisher: 'Google DeepMind',
      sourceKind: 'primary',
      publishedAt: '2026-07-07T00:00:00.000Z',
      checkedAt: CHECKED_AT,
      expiresAt: '2026-08-25T23:59:59.000Z',
      scope:
        'Konkrétna aktualizácia background execution, remote MCP, nástrojov a credential refresh.',
    },
    {
      id: 'owasp-agent-security',
      title: 'State of Agentic AI Security and Governance 2.01',
      url: 'https://genai.owasp.org/resource/state-of-agentic-ai-security-and-governance/',
      publisher: 'OWASP GenAI Security Project',
      sourceKind: 'primary',
      publishedAt: '2026-06-01T00:00:00.000Z',
      checkedAt: CHECKED_AT,
      expiresAt: '2026-09-08T23:59:59.000Z',
      scope:
        'Agent goal hijack, tool misuse, identity and privilege abuse a supply-chain riziká.',
    },
    {
      id: 'stackoverflow-ai-trust',
      title: 'Closing the developer AI trust gap',
      url: 'https://stackoverflow.blog/2026/02/18/closing-the-developer-ai-trust-gap/',
      publisher: 'Stack Overflow',
      sourceKind: 'vendor-study',
      publishedAt: '2026-02-18T00:00:00.000Z',
      checkedAt: CHECKED_AT,
      expiresAt: '2026-09-22T23:59:59.000Z',
      scope:
        'Výsledky prieskumu Stack Overflow 2025 o používaní a dôvere v AI nástroje.',
    },
    {
      id: 'anthropic-agent-survey',
      title: 'The 2026 State of AI Agents Report',
      url: 'https://resources.anthropic.com/hubfs/The%202026%20State%20of%20AI%20Agents%20Report.pdf',
      publisher: 'Anthropic',
      sourceKind: 'vendor-study',
      publishedAt: '2026-04-01T00:00:00.000Z',
      checkedAt: CHECKED_AT,
      expiresAt: '2026-10-01T23:59:59.000Z',
      scope:
        'Vendor-sponsored prieskum vyše 500 technických lídrov; závery neplatia univerzálne.',
    },
  ],
  claims: [
    {
      id: 'claim-accountability',
      kind: 'rise-opinion',
      claim: 'Rise komunikuje softvér cez zodpovednosť od rozhodnutia po prevádzku.',
      evidence: 'Verejný web a editorial principles opisujú zodpovednosť, zdroje a hranice.',
      sourceUrl: 'https://rise.sk/editorial-principles',
      checkedAt: CHECKED_AT,
      scope: 'Pozícia Rise, nie univerzálne pravidlo odvetvia.',
    },
    {
      id: 'claim-portfolio',
      kind: 'verified-fact',
      claim: 'Verejné portfólio obsahuje 11 case studies v štyroch skupinách.',
      evidence: 'Aktuálny verejný zoznam portfólia pri kontrole 24. júla 2026.',
      sourceUrl: 'https://rise.sk/portfolio',
      checkedAt: CHECKED_AT,
      scope: 'Počet sa musí v deň draftu znovu prepočítať.',
    },
    {
      id: 'claim-ai-act',
      kind: 'verified-fact',
      claim: 'Vybrané transparentnostné povinnosti AI Act sa uplatňujú od 2. augusta 2026.',
      evidence: 'Európska komisia uvádza informovanie pri interakcii s AI a označovanie vybraného obsahu.',
      sourceUrl:
        'https://digital-strategy.ec.europa.eu/en/news/commission-opens-consultation-draft-guidelines-ai-transparency-obligations',
      checkedAt: CHECKED_AT,
      scope: 'Nie všetky high-risk pravidlá začínajú v rovnaký deň; nejde o právne poradenstvo.',
    },
    {
      id: 'claim-production-agents',
      kind: 'proposed-interpretation',
      claim: 'Produkčný agent potrebuje pravidlá, povolené akcie, hodnotenie a eskaláciu.',
      evidence: 'OpenAI Presence tieto prvky uvádza ako súčasť nasadenia agentov.',
      sourceUrl: 'https://openai.com/index/introducing-openai-presence/',
      checkedAt: CHECKED_AT,
      scope: 'Interpretácia jednej aktuálnej produktovej architektúry.',
    },
    {
      id: 'claim-mapatrhu',
      kind: 'verified-fact',
      claim: 'MapaTrhu spája ponuky, cenový kontext, lokalitu a porovnanie.',
      evidence: 'Verejná case study a verejný produkt MapaTrhu.',
      sourceUrl: 'https://rise.sk/portfolio/trh-nehnutelnosti',
      checkedAt: CHECKED_AT,
      scope: 'Bez interných metrík a používateľských dát.',
    },
    {
      id: 'claim-source-workflow',
      kind: 'rise-opinion',
      claim: 'Faktické tvrdenie má mať zdroj, dôkaz, dátum kontroly a rozsah.',
      evidence: 'Verejné editorial principles Rise a interný content gate.',
      sourceUrl: 'https://rise.sk/editorial-principles',
      checkedAt: CHECKED_AT,
      scope: 'Editorial policy Rise.',
    },
    {
      id: 'claim-agent-security',
      kind: 'verified-fact',
      claim: 'OWASP pomenúva goal hijack, tool misuse, identity abuse a supply-chain riziká.',
      evidence: 'State of Agentic AI Security and Governance 2.01.',
      sourceUrl:
        'https://genai.owasp.org/resource/state-of-agentic-ai-security-and-governance/',
      checkedAt: CHECKED_AT,
      scope: 'Taxonómia rizík, nie tvrdenie o incidente Rise.',
    },
    {
      id: 'claim-grantai',
      kind: 'verified-fact',
      claim: 'GrantAI vedie od otvorenej výzvy k riadenému projektu.',
      evidence: 'Verejná case study GrantAI.',
      sourceUrl: 'https://rise.sk/portfolio/grant-ai',
      checkedAt: CHECKED_AT,
      scope: 'Bez rozpracovaných žiadostí a dát organizácií.',
    },
    {
      id: 'claim-human-control',
      kind: 'rise-opinion',
      claim: 'Rizikové zmeny a externé akcie majú zostať za ľudským schválením.',
      evidence: 'Rise editorial policy a human-gated workflow štúdia.',
      sourceUrl: 'https://rise.sk/editorial-principles',
      checkedAt: CHECKED_AT,
      scope: 'Prevádzková zásada Rise.',
    },
    {
      id: 'claim-ai-trust',
      kind: 'verified-fact',
      claim: 'Prieskum Stack Overflow ukázal rast používania AI a pokles dôvery vo výstupy.',
      evidence: 'Stack Overflow sumarizuje výsledky Developer Survey 2025.',
      sourceUrl:
        'https://stackoverflow.blog/2026/02/18/closing-the-developer-ai-trust-gap/',
      checkedAt: CHECKED_AT,
      scope: 'Prieskum respondentov Stack Overflow, nie celý trh.',
    },
    {
      id: 'claim-mojafirma',
      kind: 'verified-fact',
      claim: 'MojaFirma spája dokumenty, financie a úlohy do jedného pracovného toku.',
      evidence: 'Verejná case study MojaFirma.',
      sourceUrl: 'https://rise.sk/portfolio/ai-erp',
      checkedAt: CHECKED_AT,
      scope: 'Iba demo dáta.',
    },
    {
      id: 'claim-testing',
      kind: 'rise-opinion',
      claim: 'Odovzdanie softvéru má zahŕňať funkčnosť, prístupnosť, dáta a prevádzkové hranice.',
      evidence: 'Verejná case study vývoja Rise.sk a spôsob prezentácie kvality.',
      sourceUrl: 'https://rise.sk/portfolio/rise-sk',
      checkedAt: CHECKED_AT,
      scope: 'Procesný pohľad Rise.',
    },
    {
      id: 'claim-data-readiness',
      kind: 'proposed-interpretation',
      claim: 'Integrácie, prístup k dátam a kvalita kontextu rozhodujú o praktickom AI nasadení.',
      evidence: 'Vendor-sponsored prieskum Anthropic pomenúva integrácie a kvalitu dát ako bariéry.',
      sourceUrl:
        'https://resources.anthropic.com/hubfs/The%202026%20State%20of%20AI%20Agents%20Report.pdf',
      checkedAt: CHECKED_AT,
      scope: 'Prieskum vyše 500 technických lídrov; uviesť metodiku.',
    },
    {
      id: 'claim-smartgym',
      kind: 'verified-fact',
      claim: 'SmartGym prepája členský a prevádzkový tok cez mobil, web a vstupné zariadenie.',
      evidence: 'Verejná case study SmartGym.',
      sourceUrl: 'https://rise.sk/portfolio/smartgym',
      checkedAt: CHECKED_AT,
      scope: 'Bez členov, QR kódov a interných údajov.',
    },
    {
      id: 'claim-trnava',
      kind: 'verified-fact',
      claim:
        'Verejný analytický pohľad pre Trnavu spája mapu, linky, zastávky, tabuľky a grafy.',
      evidence: 'Verejná case study Rozvoj dopravy Trnava.',
      sourceUrl: 'https://rise.sk/portfolio/rozvoj-dopravy-trnava',
      checkedAt: CHECKED_AT,
      scope: 'Bez interných mestských dát a nepodložených dopadov.',
    },
    {
      id: 'claim-viac-nick',
      kind: 'verified-fact',
      claim:
        'Projekt VIAC AKO NI(c)K má verejne publikovanú case study s presne ohraničenými verejnými podkladmi.',
      evidence: 'Verejná case study VIAC AKO NI(c)K.',
      sourceUrl: 'https://rise.sk/portfolio/viac-ako-nick',
      checkedAt: CHECKED_AT,
      scope: 'Bez konverzácií, identít, citlivých prípadov a používateľských dát.',
    },
    {
      id: 'claim-running-app',
      kind: 'verified-fact',
      claim:
        'Verejná case study opisuje anonymizovaný mobilný proces bez identity klienta.',
      evidence: 'Verejná anonymizovaná case study bežeckej mobilnej aplikácie.',
      sourceUrl: 'https://rise.sk/portfolio/bezecka-mobilna-aplikacia',
      checkedAt: CHECKED_AT,
      scope: 'Bez reálneho UI, klienta, používateľských dát a metrík.',
    },
    {
      id: 'claim-confidentiality',
      kind: 'rise-opinion',
      claim: 'Dôvernú prácu treba vysvetliť bez predstierania, že verejné demo je klientsky systém.',
      evidence: 'Verejné case studies mzdového systému a bežeckej aplikácie používajú anonymizáciu.',
      sourceUrl: 'https://rise.sk/portfolio/personalno-mzdovy-system',
      checkedAt: CHECKED_AT,
      scope: 'Bez identity klienta a reálneho UI.',
    },
    {
      id: 'claim-modernization',
      kind: 'rise-opinion',
      claim: 'Rozhodnutie medzi postupnou modernizáciou a prestavbou závisí od rizík existujúceho systému.',
      evidence: 'Verejné príbehy vývoja Rise.sk a Slates.',
      sourceUrl: 'https://rise.sk/portfolio/rise-sk',
      checkedAt: CHECKED_AT,
      scope: 'Rozhodovací rámec, nie univerzálny verdikt.',
    },
    {
      id: 'claim-slates',
      kind: 'verified-fact',
      claim: 'Slates má verejne publikovaný dashboard a high-level architektonický pohľad.',
      evidence: 'Verejná case study Slates.',
      sourceUrl: 'https://rise.sk/portfolio/slates',
      checkedAt: CHECKED_AT,
      scope: 'Bez časového claimu a interných detailov.',
    },
    {
      id: 'claim-rastlinkovo',
      kind: 'verified-fact',
      claim: 'Rastlinkovo je verejný WooCommerce obchod optimalizovaný počas existujúcej prevádzky.',
      evidence: 'Verejná case study Rastlinkovo.',
      sourceUrl: 'https://rise.sk/portfolio/rastlinkovo',
      checkedAt: CHECKED_AT,
      scope: 'Bez obchodných metrík a administrácie.',
    },
  ],
  entries: [
    {
      id: 'accountable-software',
      publishOn: '2026-07-28',
      theme: 'human',
      title: 'Softvér, za ktorý ručíme',
      decision: 'Vysvetliť zodpovednosť Rise od prvého rozhodnutia po prevádzku.',
      projectIds: ['rise-sk', 'mapatrhu', 'grantai', 'moja-firma'],
      trendIds: [],
      claimIds: ['claim-accountability'],
      visual: {
        kind: 'branded-diagram',
        sourceType: 'original-diagram',
        sourceAsset: 'Existujúci znak Rise + štyri schválené verejné UI detaily',
        altText: 'Znak Rise prepája štyri verejné produktové ukážky.',
        redactions: ['Odstrániť všetky identifikátory z produktových detailov.'],
        aiEdited: false,
        requiresVisualApproval: false,
        cropNote: 'Znak a titulok musia zostať čitateľné v profile aj 4:5 feede.',
      },
      riskLevel: 'low',
      approvalNote: 'Štandardná editorial kontrola.',
      featured: true,
      platforms: platforms('portfolio'),
    },
    {
      id: 'ai-act-transparency',
      publishOn: '2026-07-30',
      theme: 'education',
      title: 'Čo sa mení pri AI transparentnosti od 2. augusta',
      decision: 'Oddeliť transparentnosť od zjednodušeného tvrdenia, že naraz platí celý high-risk režim.',
      projectIds: [],
      trendIds: ['ai-act-transparency'],
      claimIds: ['claim-ai-act'],
      visual: {
        kind: 'trend-diagram',
        sourceType: 'external-primary-source',
        sourceAsset: 'European Commission transparency timeline',
        altText: 'Časová os transparentnosti AI od interakcie po označenie obsahu.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'high',
      approvalNote: 'Regulovaná téma; povinná ľudská a právna kontrola formulácií.',
      featured: false,
      platforms: platforms('source'),
    },
    {
      id: 'portfolio-atlas',
      publishOn: '2026-08-05',
      theme: 'product',
      title: 'Jedenásť projektov, štyri typy problémov',
      decision: 'Ukázať šírku práce cez dôkazy, nie zoznam technológií.',
      projectIds: [
        'mapatrhu',
        'slates',
        'grantai',
        'moja-firma',
        'payroll',
        'smartgym',
        'viac-ako-nick',
        'trnava',
        'running-app',
        'rise-sk',
        'rastlinkovo',
      ],
      trendIds: [],
      claimIds: ['claim-portfolio'],
      visual: {
        kind: 'public-composite',
        sourceType: 'rise-public-asset',
        sourceAsset: 'Verejný portfolio manifest všetkých 11 case studies',
        altText: 'Mriežka verejných projektov Rise rozdelená do štyroch skupín.',
        redactions: ['Dôverné projekty použiť iba ako anonymizovaný verejný vizuál.'],
        aiEdited: true,
        requiresVisualApproval: true,
      },
      riskLevel: 'high',
      approvalNote: 'Prepočítať portfólio a schváliť každý AI-edited alebo citlivý asset.',
      featured: true,
      platforms: platforms('portfolio'),
    },
    {
      id: 'agents-beyond-chat',
      publishOn: '2026-08-11',
      theme: 'education',
      title: 'Agent už nie je iba chat',
      decision: 'Preložiť vendor novinky do checklistu úlohy, dát, povolení, evalov a eskalácie.',
      projectIds: [],
      trendIds: ['openai-presence', 'google-managed-agents'],
      claimIds: ['claim-production-agents'],
      visual: {
        kind: 'trend-diagram',
        sourceType: 'original-diagram',
        sourceAsset: 'Rise controlled-agent loop',
        altText: 'Kontrolovaný agentový tok od úlohy cez nástroje po ľudskú eskaláciu.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'medium',
      approvalNote: 'Oba primárne zdroje znovu skontrolovať do 72 hodín pred draftom.',
      featured: false,
      platforms: platforms('source'),
    },
    {
      id: 'mapatrhu-context',
      publishOn: '2026-08-13',
      theme: 'product',
      title: 'Prečo mapa bez kontextu nestačí',
      decision: 'Ukázať, ako sa ponuka, cena, lokalita a porovnanie stretávajú v jednom toku.',
      projectIds: ['mapatrhu'],
      trendIds: [],
      claimIds: ['claim-mapatrhu'],
      visual: {
        kind: 'ui-flow',
        sourceType: 'rise-public-asset',
        sourceAsset:
          '/portfolio/projects/mapatrhu/ai-edited/mapatrhu-map-search-laptop-phone-editorial.webp',
        altText: 'Mapa MapaTrhu na notebooku a detail nehnuteľnosti na telefóne.',
        redactions: ['Nepoužiť identifikujúcu adresu ani údaje ponuky.'],
        aiEdited: true,
        requiresVisualApproval: true,
      },
      riskLevel: 'medium',
      approvalNote: 'Overiť verejnosť dát a explicitne schváliť AI-edited composite.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'claim-evidence',
      publishOn: '2026-08-19',
      theme: 'human',
      title: 'Ako overujeme tvrdenia pred publikovaním',
      decision: 'Ukázať claim ID, zdroj, dôkaz, dátum a rozsah ako súčasť práce.',
      projectIds: [],
      trendIds: [],
      claimIds: ['claim-source-workflow'],
      visual: {
        kind: 'branded-diagram',
        sourceType: 'original-diagram',
        sourceAsset: 'Rise Social Studio evidence-card flow',
        altText: 'Päť krokov od tvrdenia po ľudské schválenie.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'low',
      approvalNote: 'Skontrolovať, že náhľad neobsahuje lokálne alebo súkromné zdroje.',
      featured: true,
      platforms: platforms('source'),
    },
    {
      id: 'agent-security',
      publishOn: '2026-08-25',
      theme: 'education',
      title: 'Povolenia sú súčasť AI produktu',
      decision: 'Vysvetliť agentové riziká cez hranice, povolenia a schvaľovanie.',
      projectIds: [],
      trendIds: ['owasp-agent-security'],
      claimIds: ['claim-agent-security'],
      visual: {
        kind: 'trend-diagram',
        sourceType: 'external-primary-source',
        sourceAsset: 'OWASP agentic security taxonomy redrawn in Rise visual language',
        altText: 'Hranice agenta medzi cieľom, nástrojmi, identitou a schválením.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'medium',
      approvalNote: 'Bez tvrdenia o incidente Rise alebo klienta.',
      featured: false,
      platforms: platforms('source'),
    },
    {
      id: 'grantai-workflow',
      publishOn: '2026-08-27',
      theme: 'product',
      title: 'Od otvorenej výzvy k riadenému projektu',
      decision: 'Ukázať pracovný tok GrantAI bez používateľských podkladov.',
      projectIds: ['grantai'],
      trendIds: [],
      claimIds: ['claim-grantai'],
      visual: {
        kind: 'ui-flow',
        sourceType: 'rise-public-asset',
        sourceAsset:
          '/portfolio/projects/grantai/ai-edited/grantai-dashboard-laptop-dark.webp',
        altText: 'GrantAI dashboard verejných grantových výziev na notebooku.',
        redactions: ['Žiadne organizácie, účty ani rozpracované žiadosti.'],
        aiEdited: true,
        requiresVisualApproval: true,
      },
      riskLevel: 'medium',
      approvalNote: 'Award a čísla nepoužiť bez samostatného schváleného claimu.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'human-control',
      publishOn: '2026-09-02',
      theme: 'human',
      title: 'Kde musí pri AI zostať človek',
      decision: 'Rozlíšiť návrh, automatickú akciu a akciu vyžadujúcu approval.',
      projectIds: ['grantai', 'moja-firma'],
      trendIds: [],
      claimIds: ['claim-human-control'],
      visual: {
        kind: 'branded-diagram',
        sourceType: 'original-diagram',
        sourceAsset: 'Rise automatic-versus-approved action flow',
        altText: 'Dvojkoľajný tok automatickej akcie a ľudského schválenia.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'low',
      approvalNote: 'Prezentovať ako zásadu Rise, nie zákonnú povinnosť.',
      featured: false,
      platforms: platforms('none'),
    },
    {
      id: 'ai-coding-trust',
      publishOn: '2026-09-08',
      theme: 'education',
      title: 'Používanie AI rastie. Kontrola nemôže klesnúť.',
      decision: 'Prepojiť prieskum dôvery s review, testami a ownershipom.',
      projectIds: [],
      trendIds: ['stackoverflow-ai-trust'],
      claimIds: ['claim-ai-trust'],
      visual: {
        kind: 'trend-diagram',
        sourceType: 'external-primary-source',
        sourceAsset: 'Stack Overflow survey findings redrawn as a two-axis chart',
        altText: 'Dve osi porovnávajú rast používania AI a nižšiu dôveru vo výstupy.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'high',
      approvalNote: 'Uviesť presnú metodiku a scope prieskumu pri každom čísle.',
      featured: false,
      platforms: platforms('source'),
    },
    {
      id: 'mojafirma-flow',
      publishOn: '2026-09-10',
      theme: 'product',
      title: 'Dokument, financie a úloha v jednom toku',
      decision: 'Ukázať MojaFirma cez prácu s jedným dokumentom, nie zoznam funkcií.',
      projectIds: ['moja-firma'],
      trendIds: [],
      claimIds: ['claim-mojafirma'],
      visual: {
        kind: 'ui-flow',
        sourceType: 'rise-public-asset',
        sourceAsset:
          '/portfolio/projects/mojafirma/ai-edited/mojafirma-finance-dashboard-responsive-hero.webp',
        altText: 'MojaFirma dashboard na desktopovej a mobilnej obrazovke.',
        redactions: ['Použiť iba demo firmy, dokumenty a sumy.'],
        aiEdited: true,
        requiresVisualApproval: true,
      },
      riskLevel: 'medium',
      approvalNote: 'Overiť demo dáta a explicitne schváliť AI-edited composite.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'handover-testing',
      publishOn: '2026-09-16',
      theme: 'human',
      title: 'Čo testujeme pred odovzdaním',
      decision: 'Vysvetliť funkčnosť, prístupnosť, mobil, dáta, chyby a prevádzku.',
      projectIds: ['rise-sk'],
      trendIds: [],
      claimIds: ['claim-testing'],
      visual: {
        kind: 'ui-flow',
        sourceType: 'rise-public-asset',
        sourceAsset: '/portfolio/projects/rise-sk/history/rise-home-current-2026-07.webp',
        altText: 'Aktuálny web Rise obklopený šiestimi kontrolnými bodmi.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'low',
      approvalNote: 'Kontrolný zoznam formulovať ako proces Rise.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'ai-data-readiness',
      publishOn: '2026-09-22',
      theme: 'education',
      title: 'AI projekt často stojí na dátach, nie modeli',
      decision: 'Ukázať integrácie, prístupy a kontext pod viditeľnou vrstvou modelu.',
      projectIds: ['mapatrhu', 'moja-firma'],
      trendIds: ['anthropic-agent-survey'],
      claimIds: ['claim-data-readiness'],
      visual: {
        kind: 'branded-diagram',
        sourceType: 'original-diagram',
        sourceAsset: 'Rise AI-readiness iceberg',
        altText: 'Model nad hladinou a dáta, integrácie, prístupy a kontrola pod hladinou.',
        redactions: [],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'high',
      approvalNote: 'Vendor-sponsored survey uviesť s metodikou a bez univerzálneho záveru.',
      featured: false,
      platforms: platforms('source'),
    },
    {
      id: 'smartgym-shared-state',
      publishOn: '2026-09-24',
      theme: 'product',
      title: 'Jeden stav členstva na troch miestach',
      decision: 'Vysvetliť spoločný členský stav cez mobil, web a vstupné zariadenie.',
      projectIds: ['smartgym'],
      trendIds: [],
      claimIds: ['claim-smartgym'],
      visual: {
        kind: 'public-composite',
        sourceType: 'rise-public-asset',
        sourceAsset:
          '/portfolio/projects/smartgym/ai-edited/smartgym-product-overview-three-device-mint-studio.webp',
        altText: 'SmartGym kalendár, členstvo a dashboard na troch zariadeniach.',
        redactions: ['Odstrániť mená členov a všetky QR kódy.'],
        aiEdited: true,
        requiresVisualApproval: true,
      },
      riskLevel: 'medium',
      approvalNote: 'Použiť iba verejnú case study a schváliť AI-edited composite.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'confidential-proof',
      publishOn: '2026-09-30',
      theme: 'human',
      title: 'Čo pri dôvernom projekte neukazujeme',
      decision: 'Vysvetliť rozdiel medzi verejným demom, anonymizáciou a klientskym systémom.',
      projectIds: ['payroll', 'running-app'],
      trendIds: [],
      claimIds: ['claim-confidentiality'],
      visual: {
        kind: 'public-composite',
        sourceType: 'rise-public-asset',
        sourceAsset:
          'Verejný Horilla demo tok + anonymný editorial bežec + viditeľné disclosure štítky',
        altText: 'Verejné demo a anonymný editorial vizuál vysvetľujú hranice dôverného projektu.',
        redactions: ['Žiadny klientsky screenshot, názov, výsledok ani identifikátor.'],
        aiEdited: false,
        requiresVisualApproval: true,
      },
      riskLevel: 'high',
      approvalNote: 'Povinné schválenie briefu aj každého vizuálu.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'modernize-or-rebuild',
      publishOn: '2026-10-06',
      theme: 'education',
      title: 'Prestavba alebo nový začiatok',
      decision: 'Ponúknuť rozhodovací strom podľa rizík existujúceho systému.',
      projectIds: ['rise-sk', 'slates'],
      trendIds: [],
      claimIds: ['claim-modernization'],
      visual: {
        kind: 'branded-diagram',
        sourceType: 'rise-public-asset',
        sourceAsset: 'Verejné verzie Rise.sk + high-level Slates architecture',
        altText: 'Rozhodovací strom porovnáva postupnú modernizáciu a prestavbu základu.',
        redactions: ['Slates iba na verejnej vysokej úrovni.'],
        aiEdited: false,
        requiresVisualApproval: false,
      },
      riskLevel: 'medium',
      approvalNote: 'Bez univerzálneho verdiktu a časového claimu Slates.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'slates-modernization',
      publishOn: '2026-10-08',
      theme: 'product',
      title: 'Modernizácia, ktorú možno vysvetliť bez zákulisia',
      decision: 'Ukázať verejný dashboard a high-level architektúru Slates.',
      projectIds: ['slates'],
      trendIds: [],
      claimIds: ['claim-slates'],
      visual: {
        kind: 'public-composite',
        sourceType: 'rise-public-asset',
        sourceAsset:
          '/portfolio/projects/slates/ai-edited/slates-dashboard-casting-calls-dual-laptop-dark.webp',
        altText: 'Dashboard a castingové výzvy Slates na dvoch notebookoch.',
        redactions: ['Odstrániť mená talentov a castingové identifikátory.'],
        aiEdited: true,
        requiresVisualApproval: true,
      },
      riskLevel: 'medium',
      approvalNote: 'Bez údaja o 1,5 mesiaci a so schválením AI-edited composite.',
      featured: false,
      platforms: platforms('case-study'),
    },
    {
      id: 'rastlinkovo-live-store',
      publishOn: '2026-10-14',
      theme: 'human',
      title: 'Ako zlepšovať systém, ktorý už beží',
      decision: 'Ukázať rozhodovanie pri živom e-shope bez predstierania kompletného reštartu.',
      projectIds: ['rastlinkovo'],
      trendIds: [],
      claimIds: ['claim-rastlinkovo'],
      visual: {
        kind: 'ui-flow',
        sourceType: 'rise-public-asset',
        sourceAsset:
          '/portfolio/projects/rastlinkovo/ai-edited/rastlinkovo-substrate-detail-dual-device-greenery.webp',
        altText: 'Rastlinkovo produktová stránka na notebooku a mobilný katalóg.',
        redactions: ['Žiadne objednávky, administrácia ani obchodné metriky.'],
        aiEdited: true,
        requiresVisualApproval: true,
      },
      riskLevel: 'medium',
      approvalNote: 'Použiť len verejný obchod a schváliť AI-edited composite.',
      featured: false,
      platforms: platforms('case-study'),
    },
  ],
} as const;

const PILLARS = [
  {
    id: 'product-proof',
    label: 'Produktové dôkazy',
    targetPercent: 35,
    description:
      'Verejné UI, pracovné toky a architektúra s jasnou hranicou toho, čo vieme preukázať.',
  },
  {
    id: 'decision-education',
    label: 'Rozhodnutia',
    targetPercent: 25,
    description:
      'Praktické rámce pre automatizáciu, modernizáciu, dáta a produktové kompromisy.',
  },
  {
    id: 'growth-system',
    label: 'Growth System',
    targetPercent: 15,
    description:
      'Prepojenie produktu, webu, obsahu, SEO a merania ako podporná vrstva softvéru.',
  },
  {
    id: 'people-process',
    label: 'Ľudia a proces',
    targetPercent: 15,
    description:
      'Zodpovednosť, kontrola, odovzdanie a ľudia, ktorí za výsledok ručia.',
  },
  {
    id: 'signal-noise',
    label: 'Signal vs. Noise',
    targetPercent: 10,
    description:
      'Aktuálny IT alebo AI signál oddelený od marketingového naratívu.',
  },
] as const;

const SERIES = [
  {
    id: 'inside-build',
    label: 'Inside the Build',
    description:
      'Reálne produktové dôkazy, pracovný tok, architektúra a dôležité rozhodnutie.',
  },
  {
    id: 'decision-notes',
    label: 'Decision Notes',
    description:
      'Praktické rozhodovacie rámce s možnosťami, kompromismi a odporúčaním Rise.',
  },
  {
    id: 'growth-system',
    label: 'Growth System',
    description:
      'Prepojenie produktu, webu, obsahu, SEO a merania bez marketingových skratiek.',
  },
  {
    id: 'people-behind-product',
    label: 'People Behind the Product',
    description:
      'Skutoční ľudia, pracovné momenty a zodpovednosť bez automatického hovorenia v ich mene.',
  },
  {
    id: 'signal-vs-noise',
    label: 'Signal vs. Noise',
    description:
      'Aktuálny AI alebo IT signál oddelený od marketingového naratívu a neistoty.',
  },
] as const;

type EntrySeed = {
  id: string;
  publishOn: string;
  week: number;
  slot: 'main' | 'secondary';
  pillar: (typeof PILLARS)[number]['id'];
  series:
    | 'inside-build'
    | 'decision-notes'
    | 'growth-system'
    | 'people-behind-product'
    | 'signal-vs-noise';
  title: string;
  businessGoal: string;
  buyerQuestion: string;
  risePerspective: string;
  projectIds?: string[];
  trendIds?: string[];
  claimIds: string[];
  visualTemplate:
    | 'product-anatomy'
    | 'decision-note'
    | 'before-after'
    | 'signal-noise'
    | 'human-video';
  assetKind:
    | 'real-ui'
    | 'ui-flow'
    | 'branded-diagram'
    | 'before-after'
    | 'team-photo'
    | 'trend-diagram'
    | 'public-composite'
    | 'anonymous-editorial';
  sourceType?:
    | 'rise-public-asset'
    | 'public-live-product'
    | 'original-diagram'
    | 'original-photo'
    | 'external-primary-source';
  sourceAsset: string;
  specificVisualBrief: string;
  altText: string;
  redactions?: string[];
  riskLevel?: 'low' | 'medium' | 'high';
  approvalNote: string;
  cta: string;
  linkObjective?: 'none' | 'source' | 'case-study' | 'portfolio';
  video?: boolean;
  projectClaimMode?: 'direct' | 'registry-synthesis';
  assetIds?: string[];
  assetStatus?:
    | 'owned-preview'
    | 'rights-checkpoint'
    | 'capture-required'
    | 'original-diagram';
  assetNote?: string;
};

function videoPlatforms(
  linkObjective: 'none' | 'source' | 'case-study' | 'portfolio',
) {
  return {
    instagram: {
      platform: 'instagram',
      format: 'Reel 1080 × 1920 px, 20–40 sekúnd',
      assetCount: 1,
      copyRule:
        'Prvý frame funguje bez zvuku; titulky sú povinné a caption dopĺňa jednu otázku.',
      linkObjective,
    },
    linkedin: {
      platform: 'linkedin',
      format: 'Natívne vertikálne video s titulkami',
      assetCount: 1,
      copyRule:
        'Odborný kontext a konkrétny dôkaz; video nehrá rolu všeobecného brand spotu.',
      linkObjective,
    },
    facebook: {
      platform: 'facebook',
      format: 'Krátke vertikálne video s čitateľným prvým frameom',
      assetCount: 1,
      copyRule:
        'Prirodzený lokálny text do 900 znakov a jasný odkaz na ďalší krok.',
      linkObjective,
    },
  };
}

function editorialEntry(seed: EntrySeed) {
  const riskLevel = seed.riskLevel ?? 'low';
  return {
    id: seed.id,
    publishOn: seed.publishOn,
    week: seed.week,
    slot: seed.slot,
    rolloutPhase: seed.week <= 4 ? 'pilot' : 'rollout',
    pillar: seed.pillar,
    series: seed.series,
    title: seed.title,
    businessGoal: seed.businessGoal,
    buyerQuestion: seed.buyerQuestion,
    risePerspective: seed.risePerspective,
    projectIds: seed.projectIds ?? [],
    projectClaimMode: seed.projectClaimMode ?? 'direct',
    trendIds: seed.trendIds ?? [],
    claimIds: seed.claimIds,
    visualTemplate: seed.visualTemplate,
    selectedAssetClass: seed.assetKind,
    specificVisualBrief: seed.specificVisualBrief,
    assetSelection: {
      assetIds: seed.assetIds ?? [],
      status: seed.assetStatus ?? 'original-diagram',
      note:
        seed.assetNote ??
        'Originálny vysvetľujúci diagram vznikne bez falošných dát, rozhraní alebo ľudí.',
    },
    visual: {
      kind: seed.assetKind,
      sourceType: seed.sourceType ?? 'rise-public-asset',
      sourceAsset: seed.sourceAsset,
      altText: seed.altText,
      redactions: seed.redactions ?? [],
      aiEdited: false,
      requiresVisualApproval:
        riskLevel === 'high' || seed.assetStatus === 'rights-checkpoint',
      cropNote:
        seed.video
          ? 'Tvár, titulok a produktový dôkaz držať v bezpečnej zóne vertikálneho videa.'
          : 'Kľúčový titulok a dôkaz musia zostať čitateľné v 4:5 feede aj štvorcovom oreze.',
    },
    riskLevel,
    approvalNote: seed.approvalNote,
    cta: seed.cta,
    platforms: seed.video
      ? videoPlatforms(seed.linkObjective ?? 'none')
      : platforms(seed.linkObjective ?? 'case-study'),
  };
}

const EDITORIAL_ENTRIES = [
  editorialEntry({
    id: 'w01-accountable-team',
    publishOn: '2026-07-28',
    week: 1,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'Softvér, za ktorý ručí jeden tím',
    businessGoal: 'Ukotviť Rise ako partnera, ktorý spája rozhodnutie, návrh, vývoj a prevádzku.',
    buyerQuestion: 'Kto nesie zodpovednosť, keď sa produkt presunie z návrhu do reálnej prevádzky?',
    risePerspective: 'Kupujúci nepotrebuje zoznam rolí. Potrebuje vedieť, kto udrží súvislosti a dotiahne rozhodnutia.',
    projectIds: ['rise-sk', 'mapatrhu', 'grantai', 'smartgym'],
    claimIds: [
      'claim-accountability',
      'claim-testing',
      'claim-mapatrhu',
      'claim-grantai',
      'claim-smartgym',
    ],
    visualTemplate: 'product-anatomy',
    assetKind: 'public-composite',
    sourceAsset: 'Rise-owned public portfolio UI details',
    assetIds: ['rise-home', 'mapatrhu-map', 'grantai-ui', 'smartgym-cover'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Použiť iba katalógové assety; ich práva, aktuálnosť, redakcie a finálny výber musí potvrdiť človek.',
    specificVisualBrief: 'Štyri verejné katalógové UI kandidáty v pokojnej kompozícii okolo znaku Rise; každý detail označiť projektom a pred použitím potvrdiť práva, bez metrík a notebookových mockupov.',
    altText: 'Štyri verejné produktové detaily ukazujú jeden prepojený tím Rise.',
    redactions: ['Odstrániť mená, e-maily, sumy a akékoľvek identifikátory.'],
    approvalNote: 'Iba Rise.sk detail je potvrdený ako vlastnený; klientské kandidáty aj finálny výber podliehajú ľudskému schváleniu.',
    cta: 'Pozrite si, aké typy produktov staviame.',
    linkObjective: 'portfolio',
  }),
  editorialEntry({
    id: 'w01-accountability-video',
    publishOn: '2026-07-30',
    week: 1,
    slot: 'secondary',
    pillar: 'people-process',
    series: 'people-behind-product',
    title: 'Čo pre nás znamená zodpovednosť',
    businessGoal:
      'Dať firemnej pozícii dôveryhodný ľudský hlas bez toho, aby agent hovoril v mene konkrétnej osoby.',
    buyerQuestion: 'Ako v Rise vyzerá zodpovednosť v každodennom rozhodovaní?',
    risePerspective: 'Zodpovednosť je konkrétna: pomenovať riziko, overiť dôkaz a nenechať klienta s nejasnou prevádzkou.',
    claimIds: ['claim-accountability', 'claim-human-control'],
    visualTemplate: 'human-video',
    assetKind: 'team-photo',
    sourceType: 'original-photo',
    sourceAsset: 'New approved recording of Maroš',
    assetStatus: 'capture-required',
    assetNote:
      'Fotenie alebo nahrávanie je povinné; bez schválenej nahrávky pomenovanej osoby sa vizuál nevytvorí.',
    specificVisualBrief: 'Autentický 20–40 sekundový záber Maroša v pracovnom prostredí, jedna myšlienka, prirodzené svetlo, titulky a krátky strih na verejný produktový detail.',
    altText: 'Maroš vysvetľuje, čo pre Rise znamená zodpovednosť za softvér.',
    riskLevel: 'high',
    approvalNote: 'Pomenovaná osoba musí schváliť brief, nahrávku aj finálny strih; agent nepublikuje ani nehovorí v jej mene.',
    cta: 'Napíšte nám, kde dnes vo Vašom projekte chýba jasný vlastník.',
    linkObjective: 'none',
    video: true,
  }),
  editorialEntry({
    id: 'w02-mapatrhu-context',
    publishOn: '2026-08-04',
    week: 2,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'MapaTrhu: najprv kontext, potom rozhodnutie',
    businessGoal: 'Ukázať schopnosť Rise meniť roztrúsené dáta na zrozumiteľný rozhodovací produkt.',
    buyerQuestion: 'Ako dostať ponuku, cenu a lokalitu do jedného rozhodovacieho kontextu?',
    risePerspective: 'Mapa nie je dekorácia. Je užitočná vtedy, keď spája priestor, porovnanie a ďalší krok používateľa.',
    projectIds: ['mapatrhu'],
    claimIds: ['claim-mapatrhu'],
    visualTemplate: 'product-anatomy',
    assetKind: 'real-ui',
    sourceType: 'public-live-product',
    sourceAsset: 'Public MapaTrhu map and listing UI',
    assetIds: ['mapatrhu-map'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Verejný katalógový asset MapaTrhu čaká na potvrdenie práv, čitateľnosti a redakcií.',
    specificVisualBrief: 'Šesť slidov: rozhodovacia situácia, mapa v celku, detail cenového kontextu, tok porovnania, hranica interpretácie a otázka pre kupujúceho.',
    altText: 'Verejné rozhranie MapaTrhu prepája mapu, ponuku, lokalitu a porovnanie.',
    redactions: ['Použiť iba verejné ponuky a neukazovať používateľské dáta.'],
    approvalNote: 'Použiť len aktuálne verejné rozhranie a claim z case study.',
    cta: 'Pozrite si verejnú prípadovú štúdiu MapaTrhu.',
  }),
  editorialEntry({
    id: 'w02-map-vs-table',
    publishOn: '2026-08-06',
    week: 2,
    slot: 'secondary',
    pillar: 'decision-education',
    series: 'decision-notes',
    title: 'Kedy mapa vysvetlí viac než tabuľka',
    businessGoal: 'Vzdelávať netechnického kupujúceho cez praktický formát výberu vizualizácie.',
    buyerQuestion: 'Kedy je geografický kontext naozaj dôležitý pre rozhodnutie?',
    risePerspective: 'Mapa vyhráva pri vzdialenosti, lokalite a vzoroch. Tabuľka ostáva lepšia pre presné porovnanie hodnôt.',
    projectIds: ['mapatrhu', 'trnava'],
    claimIds: ['claim-mapatrhu', 'claim-trnava'],
    visualTemplate: 'decision-note',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise map-versus-table decision diagram',
    specificVisualBrief: 'Sedemslidový rozhodovací strom s dvoma vetvami mapa versus tabuľka; doplniť jeden verejný mapový detail a pokojný záverečný checklist.',
    altText: 'Rozhodovací strom porovnáva prípady vhodné pre mapu a tabuľku.',
    approvalNote: 'Diagram je Rise interpretácia; neuvádzať univerzálny verdikt ani nepodložené výsledky.',
    cta: 'Ktorý kontext dnes vo Vašich dátach chýba?',
  }),
  editorialEntry({
    id: 'w03-rise-growth-system',
    publishOn: '2026-08-11',
    week: 3,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'Rise.sk prepája produkt, obsah a kontakt',
    businessGoal: 'Vysvetliť vlastný web ako ukážku prepojenia produktu a obchodnej cesty.',
    buyerQuestion: 'Ako má firemný web prepájať dôkaz práce s ďalším obchodným krokom?',
    risePerspective: 'Web nie je izolovaný vizuál. Portfólio, obsah, dostupnosť a kontakt musia fungovať ako jeden merateľný tok.',
    projectIds: ['rise-sk'],
    claimIds: ['claim-testing'],
    visualTemplate: 'product-anatomy',
    assetKind: 'ui-flow',
    sourceType: 'public-live-product',
    sourceAsset: 'Public Rise.sk portfolio-to-contact flow',
    assetIds: ['rise-home'],
    assetStatus: 'owned-preview',
    assetNote:
      'Rise-owned verejný asset je vhodný na lokálny náhľad; pred renderom skontrolovať aktuálnosť stránky.',
    specificVisualBrief: 'Tok z úvodnej stránky cez verejnú case study do kontaktu; použiť tri reálne obrazovky, jeden jednoduchý diagram a žiadne vymyslené analytické čísla.',
    altText: 'Verejný tok Rise.sk prepája portfólio, obsah a kontaktný krok.',
    approvalNote: 'Bez interných konverzných dát; všetky obrazovky musia byť aktuálne verejné.',
    cta: 'Prejdite si naše verejné projekty.',
    linkObjective: 'portfolio',
  }),
  editorialEntry({
    id: 'w03-web-content-seo',
    publishOn: '2026-08-13',
    week: 3,
    slot: 'secondary',
    pillar: 'growth-system',
    series: 'growth-system',
    title: 'Web, obsah, SEO a meranie ako jeden systém',
    businessGoal: 'Pozicionovať marketing ako podpornú vrstvu produktovej a softvérovej práce.',
    buyerQuestion: 'Prečo samostatná optimalizácia jednej stránky často neprinesie spoľahlivý výsledok?',
    risePerspective: 'Obsah vytvára dopyt, SEO dostupnosť, web dôkaz a meranie spätnú väzbu. Hodnotu má ich spojenie.',
    projectIds: ['rise-sk'],
    claimIds: ['claim-source-workflow', 'claim-testing'],
    visualTemplate: 'decision-note',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise Growth System loop diagram',
    specificVisualBrief: 'Kruhový, ale lineárne čitateľný diagram štyroch vrstiev: obsah, dohľadateľnosť, produktový dôkaz a meranie; pri každej vrstve jedna otázka.',
    altText: 'Diagram prepája obsah, SEO, webový dôkaz a meranie do jedného cyklu.',
    approvalNote: 'Ide o pracovný rámec Rise, nie garanciu rastu alebo pozícií vo vyhľadávaní.',
    cta: 'Skontrolujte, ktorá vrstva Vášho systému dnes chýba.',
  }),
  editorialEntry({
    id: 'w04-grantai-decision',
    publishOn: '2026-08-18',
    week: 4,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'GrantAI: skóre triedi, oprávnenosť rozhoduje',
    businessGoal: 'Ukázať AI ako kontrolovaný pracovný nástroj, nie autonómny verdikt.',
    buyerQuestion: 'Ako môže skóre pomôcť a pritom nenahradiť overenie oprávnenosti?',
    risePerspective: 'AI môže zúžiť pozornosť. Finálne rozhodnutie musí zostať opreté o pravidlá, zdroj a človeka.',
    projectIds: ['grantai'],
    claimIds: ['claim-grantai', 'claim-human-control'],
    visualTemplate: 'product-anatomy',
    assetKind: 'ui-flow',
    sourceType: 'public-live-product',
    sourceAsset: 'Public GrantAI opportunity-to-project flow',
    assetIds: ['grantai-ui'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Katalógový produktový asset GrantAI čaká na kontrolu dát a potvrdenie vizuálnych práv.',
    specificVisualBrief: 'Ukázať verejný tok výzva, orientačné skóre, kontrola podmienok a riadený projekt; farebne oddeliť návrh od rozhodnutia.',
    altText: 'Verejný tok GrantAI od výzvy cez skóre po kontrolované rozhodnutie.',
    redactions: ['Nepoužiť rozpracovanú žiadosť ani údaje organizácie.'],
    approvalNote: 'Bez tvrdenia o úspešnosti alebo automatickom schválení grantu.',
    cta: 'Pozrite si, kde v procese zostáva povinná kontrola.',
  }),
  editorialEntry({
    id: 'w04-ai-not-verdict',
    publishOn: '2026-08-20',
    week: 4,
    slot: 'secondary',
    pillar: 'decision-education',
    series: 'decision-notes',
    title: 'AI návrh nie je finálne rozhodnutie',
    businessGoal: 'Priniesť aktuálny AI signál s jasným praktickým postojom Rise.',
    buyerQuestion: 'Ktoré časti agentického toku možno automatizovať a kde treba eskaláciu?',
    risePerspective: 'Produkčný agent potrebuje povolené akcie, hodnotenie, observabilitu a cestu k človeku.',
    trendIds: ['openai-presence'],
    claimIds: ['claim-production-agents', 'claim-human-control'],
    visualTemplate: 'decision-note',
    assetKind: 'trend-diagram',
    sourceType: 'external-primary-source',
    sourceAsset: 'OpenAI Presence primary-source concepts redrawn as Rise diagram',
    specificVisualBrief: 'Šesť slidov oddelí fakt zo zdroja, marketingový naratív, prevádzkové riziko a odporúčanie Rise; záver uvedie dátum kontroly zdroja.',
    altText: 'Diagram rozlišuje AI návrh, kontrolné pravidlá, eskaláciu a ľudské rozhodnutie.',
    riskLevel: 'high',
    approvalNote: 'Rýchlo sa meniaci externý zdroj sa musí v deň draftu znovu overiť; bez generatívneho vizuálu.',
    cta: 'Pomenujte jednu akciu, ktorú by Váš agent nikdy nemal vykonať sám.',
    linkObjective: 'source',
  }),
  editorialEntry({
    id: 'w05-mojafirma-record',
    publishOn: '2026-08-25',
    week: 5,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'MojaFirma: od dokumentu k overiteľnému záznamu',
    businessGoal: 'Ukázať hodnotu pracovného toku nad dokumentmi bez odhalenia reálnych firemných dát.',
    buyerQuestion: 'Ako zmeniť dokument na dohľadateľnú úlohu alebo finančný záznam?',
    risePerspective: 'Automatizácia má zachovať pôvod, neistotu a možnosť kontroly, nie iba prepísať text do formulára.',
    projectIds: ['moja-firma'],
    claimIds: ['claim-mojafirma', 'claim-human-control'],
    visualTemplate: 'product-anatomy',
    assetKind: 'ui-flow',
    sourceAsset: 'MojaFirma public demo document flow',
    assetIds: ['mojafirma-document-flow'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Verejný katalógový diagram MojaFirma čaká na kontrolu práv, demo kontextu a čitateľnosti.',
    specificVisualBrief: 'Šesť slidov so syntetickým demo dokumentom, extrakciou, kontrolou, potvrdeným záznamom a auditnou stopou; žiadne reálne firmy ani sumy.',
    altText: 'Demo tok MojaFirma od dokumentu cez kontrolu po overiteľný záznam.',
    redactions: ['Výhradne syntetické demo dáta bez reálnych firiem, osôb a súm.'],
    approvalNote: 'Kontrola, že každý údaj je syntetický a UI zodpovedá verejnému demu.',
    cta: 'Kde dnes vo Vašom procese vzniká neoveriteľný prepis?',
  }),
  editorialEntry({
    id: 'w05-dont-automate-first',
    publishOn: '2026-08-27',
    week: 5,
    slot: 'secondary',
    pillar: 'signal-noise',
    series: 'signal-vs-noise',
    title: 'Čo by firma nemala automatizovať ako prvé',
    businessGoal: 'Pomôcť vedeniu vybrať prvý automatizačný problém podľa rizika a opakovateľnosti.',
    buyerQuestion: 'Ktorý proces je vhodný prvý kandidát a ktorý by iba zrýchlil chaos?',
    risePerspective: 'Začíname stabilným, opakovaným tokom s merateľnou chybou a jasným vlastníkom.',
    claimIds: ['claim-data-readiness', 'claim-human-control'],
    visualTemplate: 'signal-noise',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise automation readiness matrix',
    specificVisualBrief: 'Rozhodovacia matica so štyrmi osami: opakovateľnosť, kvalita vstupov, následok chyby a vlastník; bez falošného skóre alebo grafu.',
    altText: 'Matica pomáha posúdiť pripravenosť procesu na automatizáciu.',
    approvalNote: 'Ide o Rise rámec; neuvádzať ho ako univerzálnu metodiku alebo kvantitatívny model.',
    cta: 'Vyberte jeden proces a odpovedzte na štyri kontrolné otázky.',
  }),
  editorialEntry({
    id: 'w06-smartgym-shared-state',
    publishOn: '2026-09-01',
    week: 6,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'SmartGym: aplikácia, skener a web nad jedným stavom',
    businessGoal: 'Ukázať integračné myslenie na verejne opísanom viacrozhranovom produkte.',
    buyerQuestion: 'Ako udržať členstvo konzistentné medzi mobilom, webom a vstupným zariadením?',
    risePerspective: 'Rozhrania sa môžu líšiť, ale pravidlá a stav musia mať jedného vlastníka.',
    projectIds: ['smartgym'],
    claimIds: ['claim-smartgym'],
    visualTemplate: 'product-anatomy',
    assetKind: 'real-ui',
    sourceAsset: 'Public SmartGym mobile, web and scanner views',
    assetIds: ['smartgym-cover'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Verejný katalógový asset SmartGym vyžaduje kontrolu osobných údajov, QR prvkov a práv.',
    specificVisualBrief: 'Trojica verejných obrazoviek okolo jednoduchého diagramu spoločného stavu; striedať celok, detail skenera a pokojný textový slide.',
    altText: 'SmartGym prepája mobilnú aplikáciu, web a vstupné zariadenie cez spoločný stav.',
    redactions: ['Odstrániť mená členov, QR kódy a internú administráciu.'],
    approvalNote: 'Použiť iba verejnú case study a obrazovky bez identifikátorov.',
    cta: 'Pozrite si, ako sme uvažovali nad spoločným stavom.',
  }),
  editorialEntry({
    id: 'w06-source-of-truth',
    publishOn: '2026-09-03',
    week: 6,
    slot: 'secondary',
    pillar: 'decision-education',
    series: 'decision-notes',
    title: 'Prečo systémy potrebujú spoločný zdroj pravdy',
    businessGoal: 'Vysvetliť prevádzkové riziko duplikovaných stavov zrozumiteľne pre vedenie.',
    buyerQuestion: 'Čo sa stane, keď mobil, web a zariadenie rozhodujú každý samostatne?',
    risePerspective: 'Jeden zdroj pravdy neznamená jednu obrazovku. Znamená konzistentné pravidlá, identitu a audit.',
    projectIds: ['smartgym'],
    claimIds: ['claim-smartgym'],
    visualTemplate: 'decision-note',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise shared-state architecture diagram',
    specificVisualBrief: 'Diagram troch kanálov a jedného doménového stavu; jeden slide ukáže konflikt pri duplikovaní, ďalší bezpečný synchronizačný tok.',
    altText: 'Architektonický diagram ukazuje tri kanály nad jedným spoločným stavom.',
    approvalNote: 'High-level diagram bez interných implementačných detailov SmartGym.',
    cta: 'Kde sa vo Vašom systéme dnes stav duplikuje?',
  }),
  editorialEntry({
    id: 'w07-rastlinkovo-live',
    publishOn: '2026-09-08',
    week: 7,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'Rastlinkovo: optimalizácia živého e-shopu',
    businessGoal: 'Ukázať schopnosť zlepšovať existujúci produkt počas prevádzky bez vymyslených obchodných výsledkov.',
    buyerQuestion: 'Ako meniť živý e-shop bez toho, aby sa optimalizácia zmenila na nekontrolovaný redesign?',
    risePerspective: 'Najprv mapujeme cestu, obmedzenia a meranie. Potom meníme konkrétne trenie, nie všetko naraz.',
    projectIds: ['rastlinkovo'],
    claimIds: ['claim-rastlinkovo'],
    visualTemplate: 'before-after',
    assetKind: 'public-composite',
    sourceType: 'public-live-product',
    sourceAsset: 'Public Rastlinkovo storefront and approved case-study composition',
    assetIds: ['rastlinkovo-journey'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Katalógový diagram nákupnej cesty čaká na potvrdenie práv a súladu s aktuálnou case study.',
    specificVisualBrief: 'Before/After bez falošnej metriky: pôvodný kontext, miesto trenia, upravený tok, verejný detail a zoznam toho, čo by sa meralo ďalej.',
    altText: 'Verejné obrazovky Rastlinkovo ukazujú úpravu existujúcej nákupnej cesty.',
    approvalNote: 'Bez tržieb, konverzií, objednávok alebo administrácie.',
    cta: 'Pozrite si príbeh optimalizácie existujúceho obchodu.',
  }),
  editorialEntry({
    id: 'w07-journey-not-screen',
    publishOn: '2026-09-10',
    week: 7,
    slot: 'secondary',
    pillar: 'growth-system',
    series: 'growth-system',
    title: 'Zlepšujte cestu, nie iba jednu obrazovku',
    businessGoal: 'Prepojiť UX, obsah a meranie do praktického optimalizačného rámca.',
    buyerQuestion: 'Ktoré miesto v ceste brzdí používateľa pred a po konkrétnej obrazovke?',
    risePerspective: 'Obrazovka je iba jeden bod. Potrebujeme poznať vstup, očakávanie, rozhodnutie aj nasledujúci krok.',
    projectIds: ['rastlinkovo', 'rise-sk'],
    claimIds: ['claim-rastlinkovo', 'claim-testing'],
    visualTemplate: 'decision-note',
    assetKind: 'ui-flow',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise customer-journey evidence flow',
    specificVisualBrief: 'Lineárny tok vstup, očakávanie, rozhodnutie, spätná väzba a ďalší krok doplnený dvoma verejnými UI detailmi; žiadny dekoratívny funnel.',
    altText: 'Tok ukazuje širšiu používateľskú cestu okolo jednej obrazovky.',
    approvalNote: 'Rámec bez tvrdenia o konkrétnom náraste konverzie.',
    cta: 'Zmapujte jeden krok pred a jeden krok po Vašej kľúčovej obrazovke.',
  }),
  editorialEntry({
    id: 'w08-slates-modernization',
    publishOn: '2026-09-15',
    week: 8,
    slot: 'main',
    pillar: 'product-proof',
    series: 'inside-build',
    title: 'Slates: modernizácia existujúcej platformy',
    businessGoal: 'Ukázať modernizáciu ako riadenie rizika, nie ako technologický módny výber.',
    buyerQuestion: 'Ako modernizovať existujúcu platformu bez straty jej hodnotných tokov?',
    risePerspective: 'Najprv identifikujeme stabilné jadro, rizikové závislosti a používateľské toky. Až potom volíme tempo zmeny.',
    projectIds: ['slates'],
    claimIds: ['claim-slates', 'claim-modernization'],
    visualTemplate: 'before-after',
    assetKind: 'ui-flow',
    sourceAsset: 'Public Slates dashboard and high-level architecture',
    assetIds: ['slates-architecture'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Verejný katalógový diagram Slates čaká na kontrolu práv a odstránenie interných detailov.',
    specificVisualBrief: 'Striedať verejný dashboard, high-level architektúru, textový slide s hranicami a modernizačný tok; bez interného kódu a časovej metriky.',
    altText: 'Verejný dashboard a architektúra Slates vysvetľujú riadenú modernizáciu.',
    approvalNote: 'Bez mien talentov, interných detailov a neschválených časových tvrdení.',
    cta: 'Pozrite si verejný príbeh modernizácie Slates.',
  }),
  editorialEntry({
    id: 'w08-modernize-or-rewrite',
    publishOn: '2026-09-17',
    week: 8,
    slot: 'secondary',
    pillar: 'decision-education',
    series: 'decision-notes',
    title: 'Modernizovať alebo prepisovať?',
    businessGoal: 'Dať vedeniu zrozumiteľný rámec pre nákladné technologické rozhodnutie.',
    buyerQuestion: 'Kedy sa oplatí postupná modernizácia a kedy nový základ?',
    risePerspective: 'Rozhodujú doménové riziká, kvalita testov, závislosti, tempo zmeny a schopnosť prevádzkovať prechod.',
    projectIds: ['slates', 'rise-sk'],
    claimIds: ['claim-modernization', 'claim-slates'],
    visualTemplate: 'decision-note',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise modernization decision matrix',
    specificVisualBrief: 'Sedem slidov s dvoma cestami, explicitnými trade-offmi a záverečným checklistom; bez skóre, ktoré by predstieralo univerzálny verdikt.',
    altText: 'Rozhodovací rámec porovnáva postupnú modernizáciu a nový základ.',
    approvalNote: 'Ide o odborný rámec Rise, nie automatické odporúčanie pre konkrétny systém.',
    cta: 'Ktorý z piatich faktorov je vo Vašom systéme najrizikovejší?',
  }),
  editorialEntry({
    id: 'w09-trnava-data',
    publishOn: '2026-09-22',
    week: 9,
    slot: 'main',
    pillar: 'decision-education',
    series: 'decision-notes',
    title: 'Trnava: od dátového súboru k rozhodnutiu',
    businessGoal: 'Ukázať analytický produkt cez verejný tok od dát k zrozumiteľnému pohľadu.',
    buyerQuestion: 'Ako premeniť dopravné dáta na pohľad, s ktorým sa dá pracovať?',
    risePerspective: 'Dáta získajú hodnotu až s kontextom, filtrami, mapou a jasnou otázkou rozhodujúceho človeka.',
    projectIds: ['trnava'],
    claimIds: ['claim-trnava', 'claim-source-workflow'],
    visualTemplate: 'decision-note',
    assetKind: 'branded-diagram',
    sourceAsset: 'Public Trnava transport analysis screens',
    assetIds: ['trnava-decision-flow'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Verejný katalógový diagram Trnavy čaká na kontrolu práv a hraníc dát.',
    specificVisualBrief: 'Mapa, linky, zastávky, tabuľka a graf v šiestich slidoch; pri každom vizuále pomenovať rozhodovaciu otázku, nie iba typ grafu.',
    altText: 'Verejný analytický pohľad Trnavy prepája mapu, zastávky, tabuľku a graf.',
    approvalNote: 'Použiť len verejnú case study; bez interných mestských dát a nepodložených dopadov.',
    cta: 'Pozrite si, ako možno dať dátam rozhodovací kontext.',
  }),
  editorialEntry({
    id: 'w09-data-context-protection',
    publishOn: '2026-09-24',
    week: 9,
    slot: 'secondary',
    pillar: 'decision-education',
    series: 'decision-notes',
    title: 'Interná analytika potrebuje kontext aj ochranu dát',
    businessGoal: 'Vysvetliť, že interný analytický produkt je zároveň rozhodovací aj bezpečnostný systém.',
    buyerQuestion: 'Kto má vidieť ktoré dáta a v akom rozhodovacom kontexte?',
    risePerspective: 'Dobrá analytika neukazuje všetko všetkým. Spája účel, prístup, audit a zrozumiteľnú interpretáciu.',
    projectIds: ['trnava'],
    claimIds: ['claim-trnava', 'claim-source-workflow', 'claim-human-control'],
    visualTemplate: 'decision-note',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise analytics trust-boundary diagram',
    specificVisualBrief: 'Diagram dôvery s rolami, dátovými vrstvami, rozhodovacou otázkou a auditom; neukazovať reálne interné dáta ani falošný dashboard.',
    altText: 'Diagram prepája roly, dátové vrstvy, rozhodovací kontext a audit.',
    approvalNote: 'Všeobecný bezpečnostný rámec; nejde o opis interného systému mesta.',
    cta: 'Pomenujte rolu, účel a minimálne dáta pre jeden analytický pohľad.',
  }),
  editorialEntry({
    id: 'w10-payroll-flow',
    publishOn: '2026-09-29',
    week: 10,
    slot: 'main',
    pillar: 'people-process',
    series: 'people-behind-product',
    title: 'Personálno-mzdový systém: spoľahlivý pracovný tok',
    businessGoal: 'Ukázať spôsob práce na dôvernom projekte bez vymyslených metrík alebo klientského UI.',
    buyerQuestion: 'Ako navrhnúť spoľahlivý tok pre citlivé personálne a mzdové údaje?',
    risePerspective: 'Pri citlivom systéme sú hranice prístupu, validácia, odovzdanie a prevádzka rovnako dôležité ako obrazovka.',
    projectIds: ['payroll'],
    claimIds: ['claim-confidentiality', 'claim-testing'],
    visualTemplate: 'product-anatomy',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Public Horilla demo flow redrawn as Rise diagram',
    assetIds: ['payroll-architecture'],
    assetStatus: 'rights-checkpoint',
    assetNote:
      'Anonymizovaný katalógový diagram čaká na samostatné potvrdenie práv, hraníc a označenia verejného dema.',
    specificVisualBrief: 'Anonymizovaný high-level tok s jasným označením „verejné demo, nie klientsky systém“; žiadne mená, mzdy, logá klienta ani metriku 500+ bez nového verejného dôkazu.',
    altText: 'Anonymizovaný verejný demo tok personálno-mzdového systému.',
    redactions: ['Žiadny klient, zamestnanec, mzda, identita ani reálne klientské UI.'],
    riskLevel: 'high',
    approvalNote: 'Povinné schválenie briefu aj vizuálu; vizuál musí výslovne označiť verejné demo.',
    cta: 'Pozrite si, ako vysvetľujeme dôvernú prácu bez porušenia hraníc.',
  }),
  editorialEntry({
    id: 'w10-testing-handover',
    publishOn: '2026-10-01',
    week: 10,
    slot: 'secondary',
    pillar: 'people-process',
    series: 'people-behind-product',
    title: 'Testovanie, odovzdanie a prevádzková istota',
    businessGoal: 'Vysvetliť, čo Rise považuje za zodpovedné dokončenie softvéru.',
    buyerQuestion: 'Čo musí byť overené a odovzdané pred tým, než sa systém považuje za hotový?',
    risePerspective: 'Hotové neznamená iba nasadené. Znamená funkčnosť, prístupnosť, dáta, monitoring, hranice a zodpovednosť.',
    claimIds: ['claim-testing', 'claim-accountability'],
    visualTemplate: 'decision-note',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise delivery assurance checklist',
    specificVisualBrief: 'Pokojný sedemslidový checklist od akceptácie cez prístupnosť a dáta po monitoring a handover; zvýrazniť vlastníka každého kroku.',
    altText: 'Checklist zodpovedného testovania, odovzdania a prevádzkovej pripravenosti.',
    approvalNote: 'Procesný pohľad Rise; bez tvrdenia, že nahrádza konkrétny akceptačný plán.',
    cta: 'Čo dnes vo Vašom handover checkliste chýba?',
  }),
  editorialEntry({
    id: 'w11-sensitive-projects',
    publishOn: '2026-10-06',
    week: 11,
    slot: 'main',
    pillar: 'people-process',
    series: 'people-behind-product',
    title: 'Citlivé projekty bez porušenia dôvernosti',
    businessGoal: 'Budovať dôveru tým, že Rise otvorene komunikuje hranice verejnej prezentácie.',
    buyerQuestion: 'Ako môže dodávateľ ukázať spôsob práce, keď nemôže ukázať klienta ani produkt?',
    risePerspective: 'Dôvernosť nie je prázdny marketing. Ukážeme rozhodovací rámec, anonymizovaný tok a to, čo zámerne neukazujeme.',
    projectIds: ['viac-ako-nick', 'running-app'],
    claimIds: [
      'claim-viac-nick',
      'claim-running-app',
      'claim-confidentiality',
      'claim-human-control',
    ],
    visualTemplate: 'product-anatomy',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise confidentiality boundary diagram',
    assetIds: [],
    assetStatus: 'original-diagram',
    assetNote:
      'Citlivé projekty vysvetlí nový anonymizovaný diagram; nebude tvrdiť, že používa klientsky produkt alebo reálnych ľudí.',
    specificVisualBrief: 'Dvojica anonymizovaných tokov s výraznou hranicou „verejné / neverejné“; žiadne konverzácie, identity, klient, reálne bežecké UI alebo citlivé prípady.',
    altText: 'Diagram ukazuje, ktoré časti citlivého projektu možno vysvetliť verejne.',
    redactions: ['Vylúčiť identity, rozhovory, citlivé prípady, klienta, používateľské dáta a reálne UI.'],
    riskLevel: 'high',
    approvalNote: 'Povinné samostatné schválenie briefu a každého vizuálu pre oba projekty.',
    cta: 'Pozrite si verejne komunikované hranice citlivých projektov.',
  }),
  editorialEntry({
    id: 'w11-show-work-safely',
    publishOn: '2026-10-08',
    week: 11,
    slot: 'secondary',
    pillar: 'growth-system',
    series: 'growth-system',
    title: 'Ako ukázať spôsob práce a neodhaliť klienta',
    businessGoal: 'Dať praktický publikačný checklist pre dôverné softvérové projekty.',
    buyerQuestion: 'Ktorý dôkaz je bezpečný a ktorý už prezrádza klienta, údaje alebo interný systém?',
    risePerspective: 'Bezpečný príbeh oddeľuje verejný problém, náš proces a anonymizovaný model od klientského výsledku.',
    projectIds: ['payroll', 'running-app'],
    claimIds: [
      'claim-confidentiality',
      'claim-running-app',
      'claim-source-workflow',
    ],
    visualTemplate: 'decision-note',
    assetKind: 'anonymous-editorial',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise safe-disclosure editorial cards',
    specificVisualBrief: 'Sedem kariet s kontrolou identity, práv, dát, UI, metrík a výsledkov; používať iba geometrické materiálové objekty a text, nie falošných ľudí.',
    altText: 'Checklist bezpečného zverejnenia dôverného projektového príbehu.',
    riskLevel: 'high',
    approvalNote: 'Každý príklad musí prejsť ľudskou kontrolou dôvernosti a práv.',
    cta: 'Prejdite si šesť otázok pred zverejnením projektového príbehu.',
  }),
  editorialEntry({
    id: 'w12-project-synthesis',
    publishOn: '2026-10-13',
    week: 12,
    slot: 'main',
    pillar: 'growth-system',
    series: 'growth-system',
    title: 'Čo spája verejné projekty Rise',
    businessGoal: 'Uzavrieť 90 dní jasným obrazom schopností bez širokého zoznamu služieb.',
    buyerQuestion: 'Aký spoločný spôsob práce vidno naprieč rozdielnymi produktmi Rise?',
    risePerspective: 'Rozdielne produkty spája kontext problému, jeden zodpovedný tím, overiteľný tok a bezpečná prevádzka.',
    projectIds: [
      'mapatrhu',
      'slates',
      'grantai',
      'moja-firma',
      'payroll',
      'smartgym',
      'viac-ako-nick',
      'trnava',
      'running-app',
      'rise-sk',
      'rastlinkovo',
    ],
    claimIds: ['claim-portfolio', 'claim-accountability'],
    projectClaimMode: 'registry-synthesis',
    visualTemplate: 'product-anatomy',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Computed public project registry and approved public evidence',
    specificVisualBrief: 'Mapa verejných projektov odvodená z aktuálneho registra, nie ručne napísané číslo; zoskupiť podľa problému a použiť iba schválené miniatúry alebo diagram.',
    altText: 'Prehľad verejných projektov Rise zoskupený podľa riešeného problému.',
    redactions: ['Dôverné projekty reprezentovať iba schváleným anonymizovaným diagramom.'],
    riskLevel: 'high',
    approvalNote: 'Pred draftom znovu prepočítať register a skontrolovať každý projektový podklad.',
    cta: 'Nájdite projekt najbližší problému, ktorý riešite.',
    linkObjective: 'portfolio',
  }),
  editorialEntry({
    id: 'w12-learnings',
    publishOn: '2026-10-15',
    week: 12,
    slot: 'secondary',
    pillar: 'signal-noise',
    series: 'signal-vs-noise',
    title: 'Čo sme sa za 90 dní naučili',
    businessGoal: 'Vyhodnotiť pilot cez kvalitu pozornosti a obchodný signál, nie iba likes.',
    buyerQuestion: 'Ktoré otázky, dôkazy a formáty pomohli publiku rozhodovať sa lepšie?',
    risePerspective: 'Pokračujeme iba v sériách, ktoré prinášajú relevantnú pozornosť, návštevy portfólia alebo obchodné rozhovory.',
    claimIds: ['claim-source-workflow', 'claim-accountability'],
    visualTemplate: 'signal-noise',
    assetKind: 'branded-diagram',
    sourceType: 'original-diagram',
    sourceAsset: 'Rise 90-day measurement review template',
    specificVisualBrief: 'Šesť slidov bez vymyslených metrík: čo sme testovali, čo je merateľné, čo ešte nevieme, dve najlepšie série, rozhodnutie a ďalší experiment.',
    altText: 'Rámec 90-dňového vyhodnotenia obsahu bez nevyplnených falošných metrík.',
    riskLevel: 'high',
    approvalNote: 'Publikovať iba po vložení skutočných exportovaných metrík a manuálne potvrdených obchodných výsledkov.',
    cta: 'Povedzte nám, ktorý typ dôkazu Vám pomohol najviac.',
    linkObjective: 'none',
  }),
] as const;

const WEEKS = Array.from({ length: 12 }, (_, index) => {
  const number = index + 1;
  const [main, secondary] = EDITORIAL_ENTRIES.filter(
    entry => entry.week === number,
  );
  if (!main || !secondary) {
    throw new Error(`Editorial week ${number} must contain two entries.`);
  }
  return {
    number,
    phase: number <= 4 ? ('pilot' as const) : ('rollout' as const),
    label: number <= 4 ? '30-dňový pilot' : 'Ďalších 60 dní',
    mainEntryId: main.id,
    secondaryEntryId: secondary.id,
  };
});

export const RISE_CONTENT_PLAN = ContentPlanSchema.parse({
  ...LEGACY_CONTENT_PLAN,
  id: 'rise-social-studio-90-day-v2',
  startsOn: '2026-07-28',
  endsOn: '2026-10-15',
  projectRegistryCheckedAt: '2026-07-24',
  pillars: PILLARS,
  series: SERIES,
  weeks: WEEKS,
  channelRoles: [
    {
      platform: 'linkedin',
      role: 'Hlavný B2B kanál pre odbornú dôveru, rozhodovanie a projektové dôkazy.',
      evidenceFormat: 'Dva posty týždenne; aspoň jeden PDF dokument alebo multi-image.',
      successSignal: 'Relevantné komentáre, uloženia, kliky na portfólio a kvalifikované rozhovory.',
    },
    {
      platform: 'instagram',
      role: 'Vizuálny produktový magazín a ľudská tvár Rise.',
      evidenceFormat: 'Jeden carousel a jeden Reel, fotografia alebo produktový post; 2–3 Stories.',
      successSignal: 'Swipes, saves, shares, dokončenia videa a návštevy profilu.',
    },
    {
      platform: 'facebook',
      role: 'Zrozumiteľná lokálna dôvera, ľudia, projekty a návštevy webu.',
      evidenceFormat: 'Jeden až dva kratšie posty podľa vhodnosti témy.',
      successSignal: 'Relevantné reakcie, návštevy portfólia a kontaktu.',
    },
  ],
  profileFoundation: [
    {
      id: 'positioning',
      label: 'Jednotný názov, prísľub a ponuka',
      status: 'prepared',
      note: 'Rise.sk · Softvér, ktorý prináša výsledky.',
    },
    {
      id: 'logo',
      label: 'Zlatý znak Rise v kruhovom oreze',
      status: 'prepared',
      note: 'Master a 32 px kontrolný náhľad sú pripravené v profilovom packu.',
    },
    {
      id: 'covers',
      label: 'LinkedIn a Facebook covers',
      status: 'prepared',
      note: 'Sú pripravené lokálne; na živé profily neboli aplikované.',
    },
    {
      id: 'handles',
      label: 'Overiť rovnaké používateľské meno',
      status: 'needs-verification',
      note: 'Manuálne skúsiť @rise.sk, potom @risesk a @risesksoftware.',
    },
    {
      id: 'bios-links',
      label: 'Bios, specialties a UTM odkazy',
      status: 'manual-action',
      note: 'Copy-ready texty a unikátne UTM sú pripravené, zmena profilov čaká na človeka.',
    },
    {
      id: 'pinned-posts',
      label: 'Tri uvítacie pripnuté posty',
      status: 'manual-action',
      note: 'Čo staviame, ako pracujeme a vybrané projekty sa pripravia a schvália osobitne.',
    },
  ],
  cadence: {
    masterPostsPerWeek: 2,
    linkedin: '2 posty týždenne; aspoň 1 PDF carousel alebo multi-image.',
    instagram: '1 carousel + 1 Reel, fotografia alebo produktový post; 2–3 Stories.',
    facebook: '1–2 príspevky podľa vhodnosti témy.',
    verticalVideo: 'Dvakrát mesačne 20–40 sekúnd, titulky a zrozumiteľný prvý frame bez zvuku.',
  },
  kpis: [
    {
      category: 'quality',
      label: 'Kvalita a bezpečnosť',
      metrics: ['100 % claimov dohľadateľných', '0 incidentov s dôvernosťou'],
      interpretation: 'Bez tejto podmienky nemá vyšší dosah obchodnú hodnotu.',
    },
    {
      category: 'attention',
      label: 'Kvalita pozornosti',
      metrics: ['swipes', 'saves', 'shares', 'video completion', 'relevantné komentáre'],
      interpretation: 'Porovnávame medián formátov a sérií, nie jeden virálny výkyv.',
    },
    {
      category: 'interest',
      label: 'Prejavený záujem',
      metrics: ['návštevy profilu', 'portfolio clicks', 'engaged sessions', 'branded search'],
      interpretation: 'Sledujeme prechod od obsahu k verejnému dôkazu a kontaktu.',
    },
    {
      category: 'business',
      label: 'Obchodný signál',
      metrics: ['kvalifikované rozhovory', 'návštevy kontaktu', 'UTM-assisted príležitosti'],
      interpretation: 'Self-reported zdroj a UTM používame spolu; atribúciu nepredstierame ako úplnú.',
    },
  ],
  decisionRules: [
    'Vzniknú aspoň tri kvalifikované obchodné rozhovory alebo jedna reálna príležitosť.',
    'Návštevy portfólia a kontaktu zo sociálnych sietí sa oproti prvým 30 dňom zvýšia aspoň o 25 %.',
    'Dve najlepšie série dosiahnu aspoň dvojnásobný medián saves, shares a clicks oproti najslabšej sérii.',
  ],
  entries: EDITORIAL_ENTRIES,
});

export function getCanonicalPublicProjectCount(
  plan: Pick<typeof RISE_CONTENT_PLAN, 'projects'> = RISE_CONTENT_PLAN,
): number {
  return plan.projects.length;
}
